INSERT INTO usuario (nome, email, senha, matricula) values ('Administrador','admin@uea.edu.br','{bcrypt}$2a$10$X607ZPhQ4EgGNaYKt3n4SONjIv9zc.VMWdEuhCuba7oLAL5IvcL5.', '123456');
INSERT INTO usuario (nome, email, senha, matricula) values ('Maria Silva','maria@uea.edu.br','{bcrypt}$2a$10$Zc3w6HyuPOPXamaMhh.PQOXvDnEsadztbfi6/RyZWJDzimE8WQjaq', '1234567');

INSERT INTO permissao (descricao) values ('ROLE_CADASTRAR_ATIVIDADE');
INSERT INTO permissao (descricao) values ('ROLE_PESQUISAR_ATIVIDADE');
INSERT INTO permissao (descricao) values ('ROLE_ATUALIZAR_ATIVIDADE');
INSERT INTO permissao (descricao) values ('ROLE_REMOVER_ATIVIDADE');

INSERT INTO permissao (descricao) values ('ROLE_CADASTRAR_CATEGORIA');
INSERT INTO permissao (descricao) values ('ROLE_PESQUISAR_CATEGORIA');
INSERT INTO permissao (descricao) values ('ROLE_ATUALIZAR_CATEGORIA');
INSERT INTO permissao (descricao) values ('ROLE_REMOVER_CATEGORIA');

INSERT INTO permissao (descricao) values ('ROLE_CADASTRAR_COLAGEMTEMATICA');
INSERT INTO permissao (descricao) values ('ROLE_PESQUISAR_COLAGEMTEMATICA');
INSERT INTO permissao (descricao) values ('ROLE_ATUALIZAR_COLAGEMTEMATICA');
INSERT INTO permissao (descricao) values ('ROLE_REMOVER_COLAGEMTEMATICA');

INSERT INTO permissao (descricao) values ('ROLE_CADASTRAR_CURSO');
INSERT INTO permissao (descricao) values ('ROLE_PESQUISAR_CURSO');
INSERT INTO permissao (descricao) values ('ROLE_ATUALIZAR_CURSO');
INSERT INTO permissao (descricao) values ('ROLE_REMOVER_CURSO');

INSERT INTO permissao (descricao) values ('ROLE_CADASTRAR_FOTO');
INSERT INTO permissao (descricao) values ('ROLE_PESQUISAR_FOTO');
INSERT INTO permissao (descricao) values ('ROLE_ATUALIZAR_FOTO');
INSERT INTO permissao (descricao) values ('ROLE_REMOVER_FOTO');

INSERT INTO permissao (descricao) values ('ROLE_CADASTRAR_PESSOA');
INSERT INTO permissao (descricao) values ('ROLE_PESQUISAR_PESSOA');
INSERT INTO permissao (descricao) values ('ROLE_ATUALIZAR_PESSOA');
INSERT INTO permissao (descricao) values ('ROLE_REMOVER_PESSOA');

INSERT INTO permissao (descricao) values ('ROLE_CADASTRAR_PUBLICACAO');
INSERT INTO permissao (descricao) values ('ROLE_PESQUISAR_PUBLICACAO');
INSERT INTO permissao (descricao) values ('ROLE_ATUALIZAR_PUBLICACAO');
INSERT INTO permissao (descricao) values ('ROLE_REMOVER_PUBLICACAO');

INSERT INTO permissao (descricao) values ('ROLE_CADASTRAR_USUARIO');
INSERT INTO permissao (descricao) values ('ROLE_PESQUISAR_USUARIO');
INSERT INTO permissao (descricao) values ('ROLE_ATUALIZAR_USUARIO');
INSERT INTO permissao (descricao) values ('ROLE_REMOVER_USUARIO');

INSERT INTO permissao (descricao) values ('ROLE_CADASTRAR_PERMISSAO');
INSERT INTO permissao (descricao) values ('ROLE_PESQUISAR_PERMISSAO');
INSERT INTO permissao (descricao) values ('ROLE_ATUALIZAR_PERMISSAO');
INSERT INTO permissao (descricao) values ('ROLE_REMOVER_PERMISSAO');

INSERT INTO usuario_permissao (codigo_usuario,codigo_permissao) values (1, 1), (1, 2),
(1, 3), (1, 4),(1, 5), (1, 6),(1, 7), (1, 8),(1, 9), (1, 10),(1, 11), (1, 12), (1, 13), 
(1, 14),(1, 15), (1, 16), (1, 17), (1, 18), (1, 19), (1, 20), (1, 21), (1, 22), (1, 23), (1, 24), (1, 25), (1, 26)
, (1, 27), (1, 28), (1, 29), (1, 30), (1, 31), (1, 32), (1, 33), (1, 34), (1, 35), (1, 36);

INSERT INTO usuario_permissao (codigo_usuario,codigo_permissao) values (2, 2), (2, 6), (2, 10), (2, 14), (2, 18), (2, 22), (2, 26);


insert into foto (url, descricao) values ('http://tumblr.com', 'Corrosion of first degree of right thigh');
insert into foto (url, descricao) values ('https://about.me', 'Dislocation of unsp internal joint prosthesis, sequela');
insert into foto (url, descricao) values ('https://prweb.com', 'Bent bone of unsp radius, subs for clos fx w malunion');
insert into foto (url, descricao) values ('https://topsy.com', 'Toxic effect of rodenticides');
insert into foto (url, descricao) values ('http://360.cn', 'Other bursal cyst');
insert into foto (url, descricao) values ('https://wikia.com', 'Acquired atrophy of left ovary and fallopian tube');
insert into foto (url, descricao) values ('https://cbsnews.com', 'Displ apophyseal fx r femur, subs for clos fx w routn heal');
insert into foto (url, descricao) values ('https://mail.ru', 'Unspecified physeal fracture of phalanx of right toe, init');
insert into foto (url, descricao) values ('http://hc360.com', 'Pressure ulcer of left lower back, unstageable');
insert into foto (url, descricao) values ('https://com.com', 'Displaced associated transv/post fx left acetabulum, sequela');
insert into foto (url, descricao) values ('http://cmu.edu', 'Acute infarction of spinal cord (embolic) (nonembolic)');
insert into foto (url, descricao) values ('http://tinyurl.com', 'Stenosis due to internal orthopedic prosth dev/grft');
insert into foto (url, descricao) values ('https://home.pl', 'Pnctr w fb of unsp external genital organs, male, subs');
insert into foto (url, descricao) values ('http://harvard.edu', 'Arthritis due to other bacteria, unspecified ankle and foot');
insert into foto (url, descricao) values ('https://w3.org', 'Nondisp transcondy fx unsp humerus, subs for fx w delay heal');
insert into foto (url, descricao) values ('https://flickr.com', 'Displacement of indwelling urethral catheter');
insert into foto (url, descricao) values ('http://trellian.com', 'Fall from (out of) grocery cart');
insert into foto (url, descricao) values ('https://alibaba.com', 'Dvtrcli of intest, part unsp, w/o perf or abscess w bleeding');
insert into foto (url, descricao) values ('https://google.ru', 'Poisoning by antineopl and immunosup drugs, assault, sequela');
insert into foto (url, descricao) values ('https://upenn.edu', 'Other superficial bite of ear');
insert into foto (url, descricao) values ('http://prweb.com', 'Legal intervnt w manhandling, bystand injured, sequela');
insert into foto (url, descricao) values ('https://networkadvertising.org', 'Oth fracture of sacrum, subs encntr for fracture w nonunion');
insert into foto (url, descricao) values ('https://bloglines.com', 'Valgus deformity, not elsewhere classified, unspecified site');
insert into foto (url, descricao) values ('http://globo.com', 'Other exposure to forces of nature, sequela');
insert into foto (url, descricao) values ('https://shinystat.com', 'Pedal cycle rider injured in collision w rail trn/veh');
insert into foto (url, descricao) values ('https://cpanel.net', 'Traumatic rupture of unspecified ear drum, sequela');
insert into foto (url, descricao) values ('https://pen.io', 'Oth osteopor w crnt path fx, l shldr, 7thG');
insert into foto (url, descricao) values ('https://list-manage.com', 'Fracture of superior rim of right pubis, init for clos fx');
insert into foto (url, descricao) values ('https://cdbaby.com', 'Displ unsp condyle fx low end unsp femr, 7thQ');
insert into foto (url, descricao) values ('https://reverbnation.com', 'Calcific tendinitis, right ankle and foot');
insert into foto (url, descricao) values ('http://dmoz.org', 'Disp fx of prox phalanx of r great toe, 7thP');
insert into foto (url, descricao) values ('https://timesonline.co.uk', 'Unstbl burst fx second lum vert, subs for fx w delay heal');
insert into foto (url, descricao) values ('http://youtu.be', 'Legal intervnt involving oth means, bystand injured, sequela');
insert into foto (url, descricao) values ('http://deviantart.com', 'Assault by unspecified firearm discharge');
insert into foto (url, descricao) values ('https://ebay.co.uk', 'Other apnea of newborn');
insert into foto (url, descricao) values ('https://phpbb.com', 'Cocaine use, unspecified with intoxication, unspecified');
insert into foto (url, descricao) values ('http://icq.com', 'Eversion of right lacrimal punctum');
insert into foto (url, descricao) values ('https://businesswire.com', 'Complete transverse atyp femoral fracture, right leg, 7thD');
insert into foto (url, descricao) values ('https://blogger.com', 'Cereb infrc due to thombos of right middle cerebral artery');
insert into foto (url, descricao) values ('https://ted.com', 'Pretrm prem ROM, onset labor > 24 hours fol rupt, first tri');
insert into foto (url, descricao) values ('https://bluehost.com', 'Corrosion of first degree of right scapular region');
insert into foto (url, descricao) values ('https://is.gd', 'Unspecified sprain of left elbow');
insert into foto (url, descricao) values ('https://yale.edu', 'Bent bone of unspecified radius, sequela');
insert into foto (url, descricao) values ('https://gov.uk', 'Laceration w foreign body of finger w damage to nail, init');
insert into foto (url, descricao) values ('https://thetimes.co.uk', 'External constriction of left thumb, sequela');
insert into foto (url, descricao) values ('http://slate.com', 'Malignant neoplasm of right lower limb');
insert into foto (url, descricao) values ('https://auda.org.au', 'Poisoning by oth nonsteroid anti-inflam drugs, undetermined');
insert into foto (url, descricao) values ('https://macromedia.com', 'Driver of bus injured in collision w pedl cyc in traf, init');
insert into foto (url, descricao) values ('http://hexun.com', 'Oth comp of fb acc left in body fol remov cath/pack, sequela');
insert into foto (url, descricao) values ('https://fda.gov', 'Pathological fracture, right femur, subs for fx w nonunion');
insert into foto (url, descricao) values ('http://theatlantic.com', 'Fall from moving wheelchair (powered), subsequent encounter');
insert into foto (url, descricao) values ('http://g.co', 'Toxic effect of chromium and its compounds, acc, subs');
insert into foto (url, descricao) values ('https://amazon.co.uk', 'Toxic effect of ingested mushrooms, intentional self-harm');
insert into foto (url, descricao) values ('https://topsy.com', 'Inj great saphenous at hip and thigh level, unsp leg, init');
insert into foto (url, descricao) values ('http://blogger.com', 'Poisoning by oth antiprotozoal drugs, intentional self-harm');
insert into foto (url, descricao) values ('https://taobao.com', 'Fx unsp phalanx of r little finger, subs for fx w delay heal');
insert into foto (url, descricao) values ('https://cyberchimps.com', 'Inj superficial vein at shldr/up arm, right arm');
insert into foto (url, descricao) values ('https://mit.edu', 'Heat exposure on board merchant ship, initial encounter');
insert into foto (url, descricao) values ('https://drupal.org', 'Labyrinthitis');
insert into foto (url, descricao) values ('http://yale.edu', 'Unsp injury of other part of small intestine, subs encntr');

insert into categoria (nome) values ('DISCIPLINA');
insert into categoria (nome) values ('EXTENSAO');
insert into categoria (nome) values ('PESQUISA');
insert into categoria (nome) values ('RP');
insert into categoria (nome) values ('PIBID');
insert into categoria (nome) values ('PAIC');

insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Repair Cardiovascular System', 'Database Administrator I', '2023-01-15', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Marketing Assistant', 'Opn skl/oth fx/cereb lac', '2022-07-01', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Executive Secretary', 'Mal neo long bones arm', '2022-11-10', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Account Representative III', 'War inj:expl mine-cease', '2022-11-26', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Web Designer I', 'Sacroiliitis NEC', '2022-12-05', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Mechanical Systems Engineer', 'Bnign shuddering attacks', '2022-04-22', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Social Worker', 'Tarsal tunnel syndrome', '2022-11-25', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Dental Hygienist', 'TB of knee-micro dx', '2022-04-09', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Senior Cost Accountant', 'Recur dislocat-ankle', '2022-04-08', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Account Coordinator', 'Pathol dislocat-jt NEC', '2023-03-02', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Software Engineer II', 'Pancreas injury NOS-open', '2022-11-27', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Geological Engineer', 'Watercraft explos-crew', '2022-10-29', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Web Developer I', 'Abdmnal rgdt periumbilic', '2022-12-13', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Office Assistant II', 'High altitude residence', '2022-10-01', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Graphic Designer', 'Decreased WBC count NEC', '2022-06-10', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Recruiting Manager', 'Anal sphincter tear NOS', '2022-07-12', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Programmer Analyst I', 'Op skl base fx-deep coma', '2022-10-04', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Senior Quality Engineer', 'Chest swelling/mass/lump', '2022-10-04', 5, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Product Engineer', 'Gambian trypanosomiasis', '2022-04-15', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Structural Engineer', 'Adv eff cns muscl depres', '2022-10-24', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Accounting Assistant II', 'Fall-occ unpower aircraf', '2022-11-27', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Dental Hygienist', 'Anim drawn veh-pers NEC', '2022-10-24', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('VP Sales', 'Dislocat metacarpal-open', '2022-09-19', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Environmental Specialist', 'Mixed lymphosarc inguin', '2022-07-27', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Budget/Accounting Analyst I', 'Cl skull base fx-concuss', '2023-01-22', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Marketing Manager', 'Acc pois-carbn monox NOS', '2022-06-27', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Pharmacist', 'Injury abducens nerve', '2022-07-31', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Business Systems Development Analyst', 'Mycoplasma', '2022-07-21', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Account Coordinator', 'Cl skul fx NEC-deep coma', '2023-03-02', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Dental Hygienist', 'Ac stomach ulcer w hem', '2022-09-24', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Systems Administrator I', 'Contusion face/scalp/nck', '2022-12-02', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Staff Accountant I', 'Lower extremity embolism', '2022-03-26', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Senior Cost Accountant', 'TB male gen NEC-oth test', '2022-08-13', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Human Resources Manager', 'Prog ext ophthalmoplegia', '2023-03-01', 4, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Speech Pathologist', 'Anemia-other chronic dis', '2023-03-05', 3, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('General Manager', 'TB of mastoid-exam unkn', '2023-02-16', 3, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Help Desk Technician', 'Other hyperalimentation', '2022-06-14', 3, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Speech Pathologist', 'Injury-motor veh crash', '2022-07-05', 3, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Health Coach III', 'Varic vein leg-postpart', '2022-03-27', 3, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Financial Advisor', 'Cl skl fx NEC-proln coma', '2022-04-03', 3, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Assistant Professor', 'Hypertrophy of kidney', '2022-11-18', 3, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Electrical Engineer', 'Fx tibia w fibula NOS-cl', '2022-05-20', 3, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Recruiting Manager', 'Perinat jaund-hered anem', '2022-05-22', 2, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Occupational Therapist', 'Fall from cliff', '2022-06-11', 2, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Accountant III', 'Oth placent cond-deliver', '2022-10-10', 2, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Marketing Manager', 'Colon inj mult site-clos', '2023-03-06', 2, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Health Coach I', 'Ben neo lacrimal gland', '2023-01-30', 2, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Pharmacist', 'Inf mcr rst ot drg nt ml', '2022-06-14', 2, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Human Resources Assistant I', 'Hit by train-person NOS', '2022-10-02', 1, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Data Coordiator', 'Fetal-matern hem-antepar', '2023-02-12', 1, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Database Administrator IV', 'Liver lacerat unspcf opn', '2022-08-08', 1, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Structural Engineer', 'Spondylos NOS w/o myelop', '2022-08-07', 1, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Statistician IV', 'Vascular dementia,uncomp', '2022-07-11', 1, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Budget/Accounting Analyst II', 'Adv eff enzymes NEC', '2022-12-10', 1, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Paralegal', 'Priv dwel fire-accid NOS', '2022-09-28', 1, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Developer I', 'Fracture ischium-closed', '2023-03-16', 1, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Professor', 'Eye anomaly NOS', '2022-10-18', 1, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Senior Editor', 'Blood disease NOS', '2023-01-12', 1, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Assistant Media Planner', 'Vitreous disorders NEC', '2023-01-28', 1, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('Safety Technician III', 'Matern halluc af NB/fet', '2022-10-09', 1, null, null);
insert into atividade (titulo, descricao, data, codigo_categoria, codigo_usuario, codigo_publicacao) values ('VP Marketing', 'Dwarfism NEC', '2022-11-15', 1, null, null);

insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('licenciatuea', 'Ben neo lacrimal gland', '2023-03-16', true, 1, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Health Coach II', 'Deep 3 deg brn upper arm', '2022-10-08', true, 1, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Financial Analyst', 'Jt derangment NOS-shlder', '2023-03-02', false, 2, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Analyst Programmer', 'Orbital disorder NOS', '2022-08-10', true, 3, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Nuclear Power Engineer', 'Mandibular hyperplasia', '2022-07-06', true, 4, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Recruiter', 'Accidnt-mech firearm/gun', '2022-03-31', false, 5, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Graphic Designer', 'Undeterm circ-submersion', '2022-09-29', true, 6, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Junior Executive', 'Dysenter arthrit-ankle', '2022-12-31', true, 7, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Assistant Professor', 'Gonococcal endophthalmia', '2023-02-23', true, 8, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Graphic Designer', 'Neurosyphilis NEC', '2023-03-06', true, 9, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Quality Control Specialist', 'Mucosits d/t antineo rx', '2023-03-23', true, 10, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Structural Analysis Engineer', 'Mv-oth veh coll-anim rid', '2022-05-26', false, 11, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Sales Representative', 'Oth spcf preop exam', '2022-08-05', false, 12, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Payment Adjustment Coordinator', 'Fm hx genital malig NEC', '2022-06-18', false, 13, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Editor', 'Mycoplasma', '2022-05-23', true, 14, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Account Coordinator', 'Family circumstances NEC', '2022-06-26', true, 15, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Accounting Assistant I', 'Venous compl NEC-postpar', '2023-03-05', true, 16, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Office Assistant II', 'Epil par cont w/o int ep', '2022-04-23', false, 17, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('VP Accounting', 'Optic nerve hypoplasia', '2022-04-16', true, 18, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('VP Marketing', 'Extreme immat 1750-1999g', '2023-02-28', false, 19, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Registered Nurse', 'Heart chamber lacerat-cl', '2022-10-04', false, 20, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Financial Analyst', 'Sporotrichosis', '2023-02-05', false, 21, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Graphic Designer', 'Foreign bdy vulva/vagina', '2022-12-08', false, 22, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Physical Therapy Assistant', 'Fall NEC', '2022-12-02', true, 23, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('GIS Technical Architect', 'Obesity-postpartum', '2022-07-25', true, 24, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Human Resources Assistant II', 'Hemarthrosis-jt NEC', '2022-04-04', false, 25, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Editor', 'Other lymphedema', '2023-03-07', false, 26, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Senior Financial Analyst', 'Renal dis NOS-del w p/p', '2022-11-12', false, 27, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Internal Auditor', 'Opn skl base fx-coma NOS', '2022-10-21', true, 28, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('VP Sales', 'Lymphomas NEC pelvic', '2022-08-08', true, 29, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Marketing Manager', 'Subarach hem-mod coma', '2022-08-24', true, 30, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Account Executive', 'Postabortion gu infect', '2023-03-12', false, 31, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Environmental Specialist', 'Breech present-antepart', '2022-12-28', false, 32, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('VP Accounting', 'Histoplasmosis NOS', '2022-10-07', true, 33, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Geologist IV', 'Pasteurellosis', '2022-06-21', false, 34, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Research Nurse', 'Fibroadenosis of breast', '2023-03-08', true, 35, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Computer Systems Analyst II', 'Poison-spinal anesthetic', '2022-11-20', false, 36, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Quality Control Specialist', 'Fx larynx/trachea-open', '2022-08-24', true, 37, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Legal Assistant', 'Opn ang w brdrlne hi rsk', '2022-08-23', true, 38, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Marketing Manager', 'Schizophrenia NEC-remiss', '2023-02-04', true, 39, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Accounting Assistant IV', '70-79% bdy brn/20-29% 3d', '2022-08-24', true, 40, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Mechanical Systems Engineer', 'Malfunc gu dev/graft NEC', '2023-03-12', true, 41, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Payment Adjustment Coordinator', 'Postinflam optic atrophy', '2022-05-09', true, 42, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Geologist III', 'Convulsions in newborn', '2022-04-24', true, 43, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Paralegal', 'Myelodysplastic synd NOS', '2022-07-26', false, 44, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Statistician IV', 'Fecal impaction', '2022-12-08', true, 45, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Technical Writer', 'Cholestma mid ear/mstoid', '2023-03-07', false, 46, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Internal Auditor', 'Contusion of hip', '2022-06-21', false, 47, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Technical Writer', 'Terrorism,explosions', '2022-07-09', false, 48, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Operator', 'Brucella suis', '2022-09-29', false, 49, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Biostatistician I', 'Cerebel contus-prol coma', '2022-10-28', false, 50, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Chief Design Engineer', 'Air pressure change NEC', '2022-07-08', false, 51, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Web Designer IV', 'Ca in situ liver/biliary', '2022-10-08', false, 52, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Human Resources Manager', 'Int inf e coli entrnvsv', '2022-09-13', false, 53, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Actuary', 'Siderosis', '2022-07-08', false, 54, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Compensation Analyst', 'Vaccin for mumps', '2023-01-23', true, 55, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Sales Representative', 'Unc behav neo bladder', '2023-02-23', false, 56, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Cost Accountant', 'Chorea NEC', '2022-04-11', true, 57, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Staff Accountant I', 'Recur dislocat-ankle', '2022-12-19', false, 58, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Accounting Assistant III', 'Abo isoimmunizat-antepar', '2022-05-05', true, 59, null);
insert into curso (nome, descricao, data, ativo, codigo_atividade, codigo_usuario) values ('Clinical Specialist', 'Undet pois-agricult agnt', '2022-06-10', false, 60, null);

insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('asdfghjuytre', '2022-07-08', 1, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Poisoning by unsp hormone antagonists, undetermined, sequela', '2022-05-02', 1, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Disp fx of distal phalanx of right index finger, sequela', '2022-11-09', 2, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Superficial foreign body, unspecified hip, sequela', '2023-01-13', 3, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Sprain of interphalangeal joint of left thumb', '2023-02-08', 4, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Unspecified chorioretinal scars, left eye', '2022-06-01', 5, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Other contact with hot air and other hot gases, sequela', '2023-02-19', 6, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Conjunctivochalasis, left eye', '2022-05-16', 7, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Oth disrd of bone density and structure, unsp shoulder', '2023-02-14', 8, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Vitreous hemorrhage, right eye', '2022-12-08', 9, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Unsp open wound of right eyelid and periocular area, sequela', '2022-11-19', 10, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Occup of bus injured pick-up truck, pk-up/van nontraf, init', '2022-04-01', 11, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Displaced articular fracture of head of right femur, init', '2022-12-18', 12, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Poisoning by predom alpha-adrenocpt agonists, undet, init', '2022-07-31', 13, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Candidal otitis externa', '2022-11-03', 14, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Burn of unspecified degree of left toe(s) (nail), sequela', '2022-04-03', 15, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Disp fx of greater trochanter of l femr, 7thM', '2022-11-13', 16, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Lacerat extn/abdr musc/fasc/tend of right thumb at forarm lv', '2022-09-26', 17, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Activity, cross country skiing', '2022-07-22', 18, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Poisoning by local anesthetics, undetermined, sequela', '2022-04-25', 19, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Oth fracture of right lower leg, subs for clos fx w nonunion', '2022-06-18', 20, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Chagas'' disease (chronic) with heart involvement', '2022-10-12', 21, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Unsp fx upper end of l ulna, subs for clos fx w delay heal', '2022-05-29', 22, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('War operations involving firearms pellets, milt, subs', '2022-05-27', 23, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Drowning and submersion due to oth accident to fishing boat', '2022-05-20', 24, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Nondisplaced oth extrartic fracture of r calcaneus, init', '2022-10-27', 25, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Traumatic shock', '2023-02-19', 26, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Nondisp oblique fx shaft of unsp ulna, 7thP', '2022-07-30', 27, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Traumatic compartment syndrome of lower extremity', '2022-12-14', 28, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Person outside bus injured in collision w ped/anml in traf', '2022-10-02', 29, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Nondisp fx of trapezium, left wrist, subs for fx w malunion', '2023-03-16', 30, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Oth injury of blood vessel of left little finger, sequela', '2022-06-24', 31, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Disp fx of med condyle of unsp tibia, 7thN', '2022-11-25', 32, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Oth parlyt synd fol oth ntrm intcrn hemor aff left dom side', '2022-10-11', 33, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Contact with nonvenomous amphibians', '2022-03-31', 34, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Sltr-haris Type IV physeal fx upper end radius, right arm', '2023-02-23', 35, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Injury of digital nerve of thumb', '2022-04-15', 36, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Chronic follicular conjunctivitis, unspecified eye', '2023-02-04', 37, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Other injury of head of pancreas, subsequent encounter', '2022-08-25', 38, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Nondisp fx of shaft of unspecified metacarpal bone', '2023-02-24', 39, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Corrosion of first degree of unspecified axilla', '2022-07-30', 40, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Disp fx of base of second metacarpal bone. left hand', '2022-10-28', 41, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Cervical duplication', '2022-04-28', 42, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Laceration w/o fb of right thumb w/o damage to nail, init', '2022-08-16', 43, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Constant exophthalmos', '2022-06-11', 44, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Toxic effect of venom of brown recluse spider', '2022-04-23', 45, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Neoplasm of uncertain behavior of female genital organs', '2022-05-28', 46, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Adverse effect of drugs affecting uric acid metabolism, init', '2023-02-24', 47, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Familial chondrocalcinosis, multiple sites', '2022-05-11', 48, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Chronic periodontitis, localized, slight', '2023-03-04', 49, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Strain of flexor musc/fasc/tend l thm at forarm lv, subs', '2022-05-07', 50, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Poisoning by butyrophen/thiothixen neuroleptc, acc, init', '2022-08-03', 51, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Unspecified reduction defect of right lower limb', '2022-05-01', 52, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Other osteoporosis with pathological fracture, shoulder', '2023-01-06', 53, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Disp fx of neck of fourth MC bone, r hand, init for opn fx', '2023-03-06', 54, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Path fx in neopltc disease, r ulna, subs for fx w malunion', '2022-05-22', 55, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Unspecified cleft palate with bilateral cleft lip', '2022-08-02', 56, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Scoliosis, unspecified', '2022-08-21', 57, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Passenger on bus injured in collision w hv veh in traf, subs', '2023-01-24', 58, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Toxic effect of manganese and its compounds', '2022-11-07', 59, null);
insert into publicacao (descricao, data, codigo_foto, codigo_usuario) values ('Unspecified open wound of unspecified upper arm, init encntr', '2022-07-27', 60, null);

insert into colagemTematica (ordemFT, codigo_foto) values (1,30)